### ISSUE TITLE
Add openssl verification

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/sigadd#1]
Command to verify:

/usr/local/bin/openssl dgst -sha384 -verify PUBLIC_KEY -signature SIGNATURE PAYLOAD

**Comment by da1nerd** [comment]
https://github.com/unfoldingWord-dev/sigadd/blob/master/index.py#L40 will provide the link to grab the appropriate public key for verification.

**Comment by da1nerd** [comment]
can you take a look at this if you get a chance. 
Note: we don't need to strip out the org or sig from the si file. I tested it on some some older keys and signatures. However, I can't get this working for sha384.

I'm getting

```
Error Verifying Data
9664:error:0606C06E:digital envelope routines:EVP_VerifyFinal:wrong public key type:p_verify.c:85:
```

**Comment by da1nerd** [comment]
The key does appear to be correct.

```
λ openssl asn1parse -in 1426811019.22.pem
    0:d=0  hl=2 l= 118 cons: SEQUENCE
    2:d=1  hl=2 l=  16 cons: SEQUENCE
    4:d=2  hl=2 l=   7 prim: OBJECT            :id-ecPublicKey
   13:d=2  hl=2 l=   5 prim: OBJECT            :secp384r1
   20:d=1  hl=2 l=  98 prim: BIT STRING
```

**Comment by da1nerd** [comment]
part of the issue was my openssl version. I updated it to 1.0.1e and am now left with

```
Error Verifying Data
12920:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:.\crypto\asn1\tasn_dec.c:1319:
12920:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:.\crypto\asn1\tasn_dec.c:381:Type=ECDSA_SIG
```

**Comment by da1nerd** [comment]
If I base64 decode the signature first then I just get a Verification Failure.
I pushed those changes.

**Comment by jag3773** [comment]
Signature needs to be base64 decoded before running it through openssl.

**Comment by da1nerd** [comment]
facepalm. I was using the SI signature instead of the content signature. Oops!
