### ISSUE TITLE
store valid signatures in appropriate sig file

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord-dev/sigadd#2]
Once a signature is verified we'll need update the related sig file. see "Signing Content" in https://door43.org/en/dev/signing for details on where the sig file is.

**Comment by da1nerd** [comment]
what do you want to happen when a signature already exists for the si slug?

**Comment by jag3773** [comment]
Update the sig.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer
